---
- name: Install and configure Docker, deploy Apache, and serve index.html
  hosts: aws
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install prerequisites for Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Create a custom index.html
      copy:
        dest: /tmp/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello, my name is Jimmy</h1></body>
          </html>

    - name: Run Apache Docker container and mount custom index.html
      docker_container:
        name: apache_server
        image: httpd:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /tmp/index.html:/usr/local/apache2/htdocs/index.html:ro

    - name: Display Docker container status
      shell: docker ps
      register: docker_ps_output

    - name: Display Apache container running status
      debug:
        msg: "{{ docker_ps_output.stdout }}"
